### ISSUE TITLE
Plugin not work(Need Api)

### ISSUE THREAD

**Issue by xhaeffer** [PillarsZhang/PiZYDS-KeepInventory#2]
Its not work

**Comment by PillarsZhang** [comment]
Sorry,I didn't use it for a long time.
Now I am using GenisysPro which already included this function.

**Comment by PillarsZhang** [comment]
Eh...GenisysPro seems already stopped developing...

**Comment by xhaeffer** [comment]
Now... What?

**Comment by xhaeffer** [comment]
Plz fix it :(

**Comment by PillarsZhang** [comment]
Yes I see.Just need to add Api.

**Comment by xhaeffer** [comment]
so now it works?
